# google_api.pyi

def get_id_index(id_persona: int) -> int: ...

def is_expired(id_index: int) -> bool: ...

def update_static_data(id_index: int) -> None: ...

def update_dynamic_data() -> None: ...